### ISSUE TITLE
Cannot add 2+ unit on Juju 3.6-rc1. Fatal : data directory "/var/lib/postgresql/data/pgdata" has invalid permissions 0770 (PostgreSQL/initdb expects 0750 or 0700)

### ISSUE THREAD

**Issue by jeffreychang911** [canonical/postgresql-k8s-operator#760] opened 2024-11-07 15:27 UTC
## Steps to reproduce

1. deploy 3 units of postgresql-k8s on charmed kubernetes with juju 3.6-rc1

## Expected behavior
All 3 units should settle

## Actual behavior

Unit                         Workload  Agent      Address          Ports  Message
postgresql-k8s/0*            active    idle       192.168.254.136         Primary
postgresql-k8s/1             waiting   executing  192.168.252.136         awaiting for member to start
postgresql-k8s/2             waiting   executing  192.168.253.5           awaiting for cluster to start

## Versions
postgresql-k8s stable rev 381

Operating system: 

Juju CLI: 3.6-rc1

Juju agent: 3.6-rc1

Charm revision: rev 381

charmed kubernetes 1.31:

## Log output

from pod log:
2024-11-06T17:07:16.104Z [postgresql] 2024-11-06 17:07:16 UTC [14698]: user=,db=,app=,client=,line=1 FATAL:  data directory "/var/lib/postgresql/data/pgdata" has invalid permissions
2024-11-06T17:07:16.104Z [postgresql] 2024-11-06 17:07:16 UTC [14698]: user=,db=,app=,client=,line=2 DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).

## Additional context

Create this for SolQA tracking only, DPE-5915 has been created earlier.

**Comment by taurus-forever** [comment] 2024-11-07 16:10
@jeffreychang911 thank you for the bugreport, it is a duplicate of https://warthogs.atlassian.net/browse/DPE-5915, therefor resolving as we have a PR with fix there: https://github.com/canonical/postgresql-k8s-operator/pull/759

We are planning to release the new 14/stable with this commit only ASAP.

**Closed by taurus-forever** 2024-11-07 16:10 UTC
Labels: bug
