### ISSUE TITLE
'awaiting for primary endpoint to be ready' takes forever

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/postgresql-k8s-operator#54] opened 2022-10-14 14:27 UTC
it looks like patroni cannot be initilized. It might be some networking or other issue.

thus, charm is stuck in `awaiting for primary endpoint to be ready` status

another issue on top of this is that when juju emits on update status, then postgres charm sets the charm status to active with message `Primary`, which simply overrides patroni waiting message

**Comment by taurus-forever** [comment] 2022-12-09 09:10
CC: @marceloneppel 
Just for the history, fixed internally as https://warthogs.atlassian.net/browse/DPE-789 on October 14.
Resolving as no longer topical.

**Comment by beliaev-maksim** [comment] 2022-12-11 23:52
@taurus-forever 
it is not clear from Jira if the issue is fixed or not.

can you clarify on it?

**Comment by taurus-forever** [comment] 2022-12-13 08:03
You are right, the issue is not yet fixed.
My mistake. Reopened.

**Comment by arturo-seijas** [comment] 2023-03-02 08:38
This has also happened to me on a clean installation but I'm afraid the issue is intermittent. The details of my env are the following:
MicroK8s v1.26.1 revision 4595
juju 2.9.38-ubuntu-amd64

**Comment by taurus-forever** [comment] 2023-03-02 12:00
Dear @arturo-seijas , thank you for bumping this up!
The issue had low priority due to random reproducibility. Searching for steps-to-reproduce reliably.
The priority revised to investigate it further the next pulse `23#6`.

Is it constantly reproducible for you? Any specific actions to reproduce it?
I have fired new multipass machine and postgresql (revision 47) started properly:
```
> multipass launch -c8 -m8Gb -d30Gb charm-dev
...
> multipass shell charm-dev

> juju deploy postgresql-k8s --channel edge --trust
Located charm "postgresql-k8s" in charm-hub, revision 47
Deploying "postgresql-k8s" from charm-hub charm "postgresql-k8s", revision 47 in channel edge on jammy
...

> juju status
Model       Controller  Cloud/Region        Version  SLA          Timestamp
default38x  microk8s    microk8s/localhost  2.9.38   unsupported  11:56:36+01:00

App             Version  Status  Scale  Charm           Channel  Rev  Address         Exposed  Message
postgresql-k8s           active      1  postgresql-k8s  edge      47  10.152.183.238  no       Primary

Unit               Workload  Agent  Address     Ports  Message
postgresql-k8s/0*  active    idle   10.1.84.81         Primary

> snap list | grep 'microk8s\|juju'
juju        2.9.38         21790  2.9/stable     canonical**  classic
microk8s    v1.26.1        4595   1.26/stable    canonical**  classic
```

I will continue searching the way to reproduce the issue reliably and will share my findings.

**Comment by arturo-seijas** [comment] 2023-03-02 12:02
Hi @taurus-forever,

No, haven't been able to reproduce it since, but I'll keep an eye on it too.

Thanks

**Comment by marceloneppel** [comment] 2023-03-23 20:22
I implemented a fix through https://github.com/canonical/postgresql-k8s-operator/pull/116 for the original situation reported by Maksim (he reported me on MM that something might got wrong with microk8s network, after that some pods died, but PG hasn't recovered).

@arturo-seijas, can you try revision 58 (the latest on edge) and see if you face the issue again? If so, can we get more details about how are you deploying?

**Comment by arturo-seijas** [comment] 2023-03-24 09:55
> I implemented a fix through #116 for the original situation reported by Maksim (he reported me on MM that something might got wrong with microk8s network, after that some pods died, but PG hasn't recovered).
> 
> @arturo-seijas, can you try revision 58 (the latest on edge) and see if you face the issue again? If so, can we get more details about how are you deploying? I tried revision 47 in an environment similar to yours (same Juju and microk8s version), but couldn't reproduce the error.

I haven't been able to reproduce the issue with revision 58. As far as I'm concerned, I think we can close the ticket. Thank you very much

**Comment by beliaev-maksim** [comment] 2023-03-24 10:44
@marceloneppel I am +1 for closing considering #116

**Comment by marceloneppel** [comment] 2023-03-24 19:29
Thanks @arturo-seijas and @beliaev-maksim!

**Closed by marceloneppel** 2023-03-24 19:29 UTC
Labels: bug
