### ISSUE TITLE
Missing `cluster-initialised` flag causes cluster to become stuck

### ISSUE THREAD

**Issue by AmberCharitos** [canonical/postgresql-k8s-operator#634] opened 2024-08-15 08:27 UTC
## Steps to reproduce

This was seen in production, the below is what happened in production. This does not necessarily mean it will reproduce the same bug locally as there may have been other factors at play. 

1. Deploy 3 units of postgresql-k8s charm channel 14/edge revision 198.
2. Restart all pods the same time.

## Expected behavior
All units come back to an active status

## Actual behavior
All units enter either maintenance or waiting status. With the following, cluster not initialized log message.
```
Re-emitting deferred event <PebbleReadyEvent via PostgresqlOperatorCharm/on/postgresql_pebble_ready[6552765]>.
unit-postgresql-db-0: 08:13:00 DEBUG unit.postgresql-db/0.juju-log Deferring on_postgresql_pebble_ready: Not leader and cluster not initialized

```

## Versions

Operating system: Ubuntu 22.04.4 LTS

Juju CLI: 3.5.3-ubuntu-amd64

Juju agent: 3.1.8

Charm revision: `198` `14/edge`

kubectl:
Client Version: v1.30.3
Server Version: v1.26.15

## Log output

Juju debug log: 

[postgresql-0.log](https://github.com/user-attachments/files/16623037/postgresql-0.log)
[postgresql-1.log](https://github.com/user-attachments/files/16623039/postgresql-1.log)
[postgresql-2.log](https://github.com/user-attachments/files/16623043/postgresql-2.log)

## Additional context

[Matrix conversation for context] (https://matrix.to/#/!BukWfnyOTgQSKAxdtT:ubuntu.com/$jrGfGfW07m4i6t0dKcKAElmZmEznSvDlh1ruRTerFgI?via=ubuntu.com&via=matrix.org&via=laquadrature.net)

**Comment by marceloneppel** [comment] 2024-08-16 17:55
Thanks for the bug report, @AmberCharitos!

Just to not forget, the flag is removed at https://github.com/canonical/postgresql-k8s-operator/blob/e760a3df8ceceab49357ff57c620299d9d101fc8/src/charm.py#L841.

**Comment by lucasgameiroborges** [comment] 2024-11-06 19:40
Hi @AmberCharitos, thanks for the bug report!

Question: Have you observed this issue on newer charm revisions? I haven't been able to reproduce this issue locally, the charm seems to consistently recover in around 2 minutes after doing `kubectl delete pod pg-0 pg-1 pg-2`. Do you have specific steps?

It seems like we even have this case covered in an integration test: https://github.com/canonical/postgresql-k8s-operator/blob/ea87ed7eb9c42f96eb112ac27b266ad49db61648/tests/integration/ha_tests/test_restart.py#L73-L79 from @marceloneppel 

A lot has changed since revision `198`, so this might have been fixed in subsequent patches.

**Comment by AmberCharitos** [comment] 2024-11-07 10:01
Hi @lucasgameiroborges I don't believe I have seen it since upgrading revision. Happy for you to close this since `198` was a long time ago and a lot has changed since then.

**Comment by lucasgameiroborges** [comment] 2024-11-07 11:41
Nice! Feel free to reopen or reach out if it ever happens again!

**Closed by lucasgameiroborges** 2024-11-07 11:41 UTC
Labels: bug
